{
  "hash": "c34b54526a86becbf2494403cf3d8252",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Your Name Here\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(dplyr)\nlibrary(tigris)\noptions(tigris_use_cache = TRUE, tigris_class = \"sf\")\nlibrary(tidycensus)\nlibrary(knitr)\nlibrary(ggplot2)\nlibrary(scales)\n\n# Load spatial data\n# counties: shapefile in data/\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\", quiet = TRUE)\n# hospitals: GeoJSON in data/\nhospitals <- st_read(\"data/hospitals.geojson\", quiet = TRUE)\n# census tracts: from tigris\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE, year = 2023)\n\n# Make CRS consistent with counties\nhospitals     <- st_transform(hospitals,     st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\n# Check that all data loaded correctly\nlist(\n  rows_counties   = nrow(pa_counties),\n  rows_hospitals  = nrow(hospitals),\n  rows_tracts     = nrow(census_tracts),\n  crs_counties    = st_crs(pa_counties)$input,\n  crs_hospitals   = st_crs(hospitals)$input,\n  crs_tracts      = st_crs(census_tracts)$input,\n  geom_counties   = unique(st_geometry_type(pa_counties)),\n  geom_hospitals  = unique(st_geometry_type(hospitals)),\n  geom_tracts     = unique(st_geometry_type(census_tracts))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$rows_counties\n[1] 67\n\n$rows_hospitals\n[1] 223\n\n$rows_tracts\n[1] 3445\n\n$crs_counties\n[1] \"WGS 84 / Pseudo-Mercator\"\n\n$crs_hospitals\n[1] \"WGS 84 / Pseudo-Mercator\"\n\n$crs_tracts\n[1] \"WGS 84 / Pseudo-Mercator\"\n\n$geom_counties\n[1] MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n\n$geom_hospitals\n[1] POINT\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n\n$geom_tracts\n[1] MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\nThere are 223 hospitals in Pennsylvania according to the provided dataset.\nThere are 3,445 census tracts across the state.\nAll three layers (counties, hospitals, tracts) are currently in WGS 84 / Pseudo-Mercator (EPSG:3857).\n---\n\n#### Step 2: Get Demographic Data \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n# 1) Set ACS year\nacs_year <- 2022   # most recent 5-year estimates\n\n# 2) Variables:\n# B01003_001 = total population\n# B19013_001 = median household income\n# B01001_020 + B01001_021 + B01001_044 + B01001_045 = age 65+ (male + female groups)\nvars <- c(\n  total_pop = \"B01003_001\",\n  median_income = \"B19013_001\",\n  male65_66   = \"B01001_020\",\n  male67_69   = \"B01001_021\",\n  male70_74   = \"B01001_022\",\n  male75_79   = \"B01001_023\",\n  male80_84   = \"B01001_024\",\n  male85plus  = \"B01001_025\",\n  female65_66 = \"B01001_044\",\n  female67_69 = \"B01001_045\",\n  female70_74 = \"B01001_046\",\n  female75_79 = \"B01001_047\",\n  female80_84 = \"B01001_048\",\n  female85plus= \"B01001_049\"\n)\n\n# 3) Pull ACS data at tract level for PA\npa_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = vars,\n  year = acs_year,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\n# 4) Compute elderly population (sum male+female 65+)\npa_demo <- pa_demo %>%\n  mutate(\n    over65 = male65_66E + male67_69E + male70_74E + male75_79E + \n             male80_84E + male85plusE + \n             female65_66E + female67_69E + female70_74E +\n             female75_79E + female80_84E + female85plusE\n  ) %>%\n  select(GEOID, total_popE, median_incomeE, over65)\n\n# 5) Join to tract boundaries\ncensus_tracts_demo <- census_tracts %>%\n  left_join(pa_demo, by = \"GEOID\")\n\n# How many tracts missing income?\nmissing_income <- sum(is.na(census_tracts_demo$median_incomeE))\n# Median income across all tracts (ignoring missing)\noverall_median_income <- median(census_tracts_demo$median_incomeE, na.rm = TRUE)\nlist(\n  acs_year_used = acs_year,\n  n_tracts = nrow(census_tracts_demo),\n  missing_income_tracts = missing_income,\n  median_income_all_tracts = overall_median_income\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$acs_year_used\n[1] 2022\n\n$n_tracts\n[1] 3445\n\n$missing_income_tracts\n[1] 62\n\n$median_income_all_tracts\n[1] 70188\n```\n\n\n:::\n:::\n\n\nACS year used: 2022 (5-year estimates)\nNumber of census tracts in dataset: 3,445\nTracts with missing income data: 62\nMedian household income across all PA tracts: $70,188\n---\n\n#### Step 3: Define Vulnerable Populations \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# 1) Define thresholds\nincome_threshold <- 50000 # $50,000 income\nelderly_pct_threshold <- 0.17 # 17% elderly\n\n# 2) Compute elderly percentage\ncensus_tracts_demo <- census_tracts_demo %>%\n  mutate(\n    pct_over65 = over65 / total_popE,\n    vulnerable = if_else(median_incomeE < income_threshold & pct_over65 > elderly_pct_threshold, 1, 0)\n  )\n\n# 3) Summary counts\nn_vulnerable <- sum(census_tracts_demo$vulnerable, na.rm = TRUE)\nn_total <- nrow(census_tracts_demo)\npct_vulnerable <- round(100 * n_vulnerable / n_total, 1)\n\nlist(\n  income_threshold = income_threshold,\n  elderly_threshold = elderly_pct_threshold,\n  vulnerable_tracts = n_vulnerable,\n  pct_vulnerable = pct_vulnerable\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$income_threshold\n[1] 50000\n\n$elderly_threshold\n[1] 0.17\n\n$vulnerable_tracts\n[1] 253\n\n$pct_vulnerable\n[1] 7.3\n```\n\n\n:::\n:::\n\n\nI chose $50,000 as the income threshold. This is well below Pennsylvania’s overall tract-level median income of about $70,000.\nI chose 17% elderly population as the threshold, which is slightly above the national average (~16–17%).\nThere are 524 census tracts in Pennsylvania that meet the vulnerability criteria.\nAbout 7.3% of Pennsylvania’s 3,445 census tracts fall into this vulnerable category.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\ncensus_tracts_proj <- st_transform(census_tracts_demo, 5070)\nhospitals_proj <- st_transform(hospitals, 5070)\n\n# Calculate distance from each tract centroid to nearest hospital\ntract_centroids <- st_centroid(census_tracts_proj)\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\ntract_centroids$nearest_hosp_dist_m <- apply(dist_matrix, 1, min)\ntract_centroids$nearest_hosp_dist_mi <- tract_centroids$nearest_hosp_dist_m / 1609.34\n\nvulnerable_tracts_dist <- tract_centroids %>%\n  filter(vulnerable == 1) %>%\n  st_drop_geometry() %>%\n  select(GEOID, median_incomeE, pct_over65, nearest_hosp_dist_mi)\n\nsummary_stats <- summary(vulnerable_tracts_dist$nearest_hosp_dist_mi)\nsummary_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n 0.02107  0.83908  1.80602  3.27466  3.55821 18.64304 \n```\n\n\n:::\n:::\n\n\n\nThis projection uses meters as its unit, which avoids distortions from geographic CRS like WGS84 (degrees), so distances can be directly converted to miles.\n\nThe average distance is about 3.27 miles.\nThe maximum distance from a vulnerable tract centroid to the nearest hospital is about 18.6 miles.\nBy checking the distance distribution, only a small number of vulnerable tracts (likely fewer than 5) are more than 15 miles away.\n---\n\n#### Step 5: Identify Underserved Areas \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\ntract_centroids <- tract_centroids %>%\n  mutate(\n    underserved = if_else(vulnerable == 1 & nearest_hosp_dist_mi > 15, 1, 0)\n  )\n\nn_underserved <- sum(tract_centroids$underserved, na.rm = TRUE)\nn_vulnerable <- sum(tract_centroids$vulnerable, na.rm = TRUE)\npct_underserved <- round(100 * n_underserved / n_vulnerable, 1)\n\nlist(\n  underserved_tracts = n_underserved,\n  vulnerable_tracts_total = n_vulnerable,\n  pct_vulnerable_underserved = pct_underserved\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$underserved_tracts\n[1] 7\n\n$vulnerable_tracts_total\n[1] 253\n\n$pct_vulnerable_underserved\n[1] 2.8\n```\n\n\n:::\n:::\n\n\n7 tracts meet the definition. 2.8% of vulnerable tracts are undeserved.This result is not very surprising. Most of Pennsylvania’s population—and thus its healthcare infrastructure—is concentrated in urban and suburban counties. Rural areas may have some underserved tracts, but they are relatively few in number.\n\n---\n\n#### Step 6: Aggregate to County Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties_proj <- st_transform(pa_counties, 5070)\ntract_centroids_proj <- st_transform(tract_centroids, 5070)\ntracts_with_county <- st_join(tract_centroids_proj, pa_counties_proj, join = st_within)\n\n# Aggregate statistics by county\ncounty_stats <- tracts_with_county %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = ifelse(vulnerable_tracts > 0,\n                             100 * underserved_tracts / vulnerable_tracts, NA),\n    avg_distance_vuln_mi = mean(nearest_hosp_dist_mi[vulnerable == 1], na.rm = TRUE),\n    vulnerable_population = sum(over65[vulnerable == 1], na.rm = TRUE) # 65+ as proxy for vulnerable pop\n  ) %>%\n  arrange(desc(pct_underserved))\n\nhead(county_stats, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   COUNTY_NAM vulnerable_tracts underserved_tracts pct_underserved\n   <chr>                  <dbl>              <dbl>           <dbl>\n 1 CAMERON                    1                  1           100  \n 2 FOREST                     2                  2           100  \n 3 MONROE                     1                  1           100  \n 4 CLEARFIELD                 3                  2            66.7\n 5 JUNIATA                    2                  1            50  \n 6 ADAMS                      1                  0             0  \n 7 ALLEGHENY                 49                  0             0  \n 8 ARMSTRONG                  1                  0             0  \n 9 BEAVER                     8                  0             0  \n10 BEDFORD                    2                  0             0  \n# ℹ 2 more variables: avg_distance_vuln_mi <dbl>, vulnerable_population <dbl>\n```\n\n\n:::\n:::\n\n\nCameron (100%) – 1 vulnerable tract, and it is underserved.\nForest (100%) – 2 vulnerable tracts, both underserved.\nMonroe (100%) – 1 vulnerable tract, underserved.\nClearfield (66.7%) – 3 vulnerable tracts, 2 underserved.\nJuniata (50%) – 2 vulnerable tracts, 1 underserved.\nFrom the current table, counties like Cameron, Forest, and Clearfield stand out, because although they don’t have many tracts, nearly all of their vulnerable tracts are underserved and the average distance to the nearest hospital is 15–19 miles.\nYes. The underserved counties are concentrated in rural and sparsely populated areas (Northern and Central Pennsylvania: Cameron, Forest, Clearfield, Juniata). These counties have few hospitals and residents often face long travel times.\n---\n\n#### Step 7: Create Summary Table \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\npriority_counties <- county_stats %>%\n  mutate(\n    `% Underserved` = round(pct_underserved, 1),\n    `Avg Distance (mi)` = round(avg_distance_vuln_mi, 1),\n    `Vulnerable Pop (65+)` = comma(vulnerable_population)\n  ) %>%\n  arrange(desc(`% Underserved`), desc(as.numeric(gsub(\",\", \"\", `Vulnerable Pop (65+)`)))) %>%\n  slice(1:10) %>%\n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = vulnerable_tracts,\n    `Underserved Tracts` = underserved_tracts,\n    `% Underserved`,\n    `Avg Distance (mi)`,\n    `Vulnerable Pop (65+)`\n  )\n\nkable(\n  priority_counties,\n  caption = \"Top 10 Pennsylvania Counties with Highest Priority for Healthcare Investment (based on underserved vulnerable tracts and population needs)\",\n  align = \"lccccc\",\n  format = \"markdown\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Pennsylvania Counties with Highest Priority for Healthcare Investment (based on underserved vulnerable tracts and population needs)\n\n|County       | Vulnerable Tracts | Underserved Tracts | % Underserved | Avg Distance (mi) | Vulnerable Pop (65+) |\n|:------------|:-----------------:|:------------------:|:-------------:|:-----------------:|:--------------------:|\n|FOREST       |         2         |         2          |     100.0     |       18.3        |        1,593         |\n|CAMERON      |         1         |         1          |     100.0     |       18.6        |         428          |\n|MONROE       |         1         |         1          |     100.0     |       17.6        |         314          |\n|CLEARFIELD   |         3         |         2          |     66.7      |       15.5        |        2,083         |\n|JUNIATA      |         2         |         1          |     50.0      |       12.6        |        1,332         |\n|PHILADELPHIA |        38         |         0          |      0.0      |        1.0        |        32,275        |\n|ALLEGHENY    |        49         |         0          |      0.0      |        2.2        |        27,071        |\n|WESTMORELAND |        14         |         0          |      0.0      |        3.2        |        8,023         |\n|LUZERNE      |        10         |         0          |      0.0      |        3.2        |        7,619         |\n|FAYETTE      |         9         |         0          |      0.0      |        3.6        |        7,158         |\n\n\n:::\n:::\n\n\n\n## Part 2: Comprehensive Visualization \n\n### Map 1: County-Level Choropleth \n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(sf)\nlibrary(scales)\n\npa_counties_map <- pa_counties_proj %>%\n  left_join(\n    county_stats %>%\n      mutate(pct_underserved = as.numeric(pct_underserved)),\n    by = c(\"COUNTY_NAM\")\n  )\n\nggplot() +\n  geom_sf(\n    data = pa_counties_map,\n    aes(fill = pct_underserved),\n    color = \"white\", size = 0.25\n  ) +\n  geom_sf(\n    data = hospitals_proj,\n    shape = 21, fill = \"black\", color = \"white\", size = 1.4, alpha = 0.7\n  ) +\n  scale_fill_viridis_c(\n    name = \"% Underserved (of vulnerable tracts)\",\n    labels = function(x) paste0(x, \"%\"),\n    na.value = \"grey90\",\n    option = \"-magma\",\n    limits = c(0, 100)\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percent of vulnerable counties that are >15 miles from the nearest hospital\",\n    caption = \"Sources: ACS 2022 5-year (tidycensus), lecture hospital data, county boundaries\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text  = element_text(size = 9),\n    plot.title   = element_text(size = 14, face = \"bold\"),\n    plot.subtitle= element_text(size = 11),\n    plot.caption = element_text(size = 8, color = \"grey30\"),\n    panel.background = element_rect(fill = \"grey98\", color = NA)\n  )\n```\n\n::: {.cell-output-display}\n![](Luciano_Lu_assignment2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntracts_final <- census_tracts_demo %>%\n  left_join(\n    tract_centroids %>%\n      st_drop_geometry() %>%\n      select(GEOID, nearest_hosp_dist_mi, vulnerable, underserved),\n    by = \"GEOID\"\n  )\n\nggplot() +\n  geom_sf(\n    data = tracts_final,\n    aes(fill = factor(underserved, levels = c(0, 1), labels = c(\"Not Underserved\", \"Underserved\"))),\n    color = \"white\", size = 0.1\n  ) +\n  geom_sf(\n    data = pa_counties_proj,\n    fill = NA, color = \"black\", size = 0.3\n  ) +\n  geom_sf(\n    data = hospitals_proj,\n    shape = 21, fill = \"black\", color = \"white\", size = 1.2, alpha = 0.7\n  ) +\n  scale_fill_manual(\n    name = \"Vulnerability Status\",\n    values = c(\"Not Underserved\" = \"#4C78A8\", \"Underserved\" = \"#D62728\"),\n    na.value = \"grey90\"\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Vulnerable tracts are those with low income and high elderly populations\",\n    caption = \"Sources: ACS 2022 (tidycensus), lecture hospital data, county boundaries\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text  = element_text(size = 9),\n    plot.title   = element_text(size = 14, face = \"bold\"),\n    plot.subtitle= element_text(size = 11),\n    plot.caption = element_text(size = 8, color = \"grey30\"),\n    panel.background = element_rect(fill = \"grey98\", color = NA)\n  )\n```\n\n::: {.cell-output-display}\n![](Luciano_Lu_assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nvuln <- tract_centroids %>%\n  st_drop_geometry() %>%\n  filter(vulnerable == 1)\n\nggplot(vuln, aes(x = nearest_hosp_dist_mi)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"#4C78A8\", color = \"white\", alpha = 0.9) +\n  geom_density(linewidth = 1) +\n  labs(\n    title = \"Distance to Nearest Hospital (Vulnerable Tracts)\",\n    x = \"Distance (miles)\",\n    y = \"Density\",\n    caption = \"Most vulnerable tracts are located within 5 miles of the nearest hospital, though a small number of rural tracts face much longer travel distances (up to ~18 miles).\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](Luciano_Lu_assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Part 3: Own Data Analysis \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n# ---- Load Schools (fixed) ----\nlibrary(sf)\nlibrary(dplyr)\n\nschools_path <- \"data/schools.geojson\"\n\nschools <- st_read(schools_path, quiet = TRUE) |>\n  st_make_valid() |>\n  st_transform(2272) |>\n  mutate(\n    enrollment_num = suppressWarnings(as.numeric(gsub(\"[^0-9.]\", \"\", enrollment))),\n    type_specific  = as.character(type_specific),\n    grade_level    = as.character(grade_level),\n    grade_org      = as.character(grade_org)\n  )\n\nn_schools <- nrow(schools)\ncrs_label <- st_crs(schools)$input\nbbox_ft   <- st_bbox(schools)\n\ntype_by_specific <- schools |>\n  st_drop_geometry() |>\n  count(type_specific, name = \"n\", sort = TRUE)\n\ntype_by_code <- schools |>\n  st_drop_geometry() |>\n  count(type, name = \"n\", sort = TRUE)\n\nby_grade_level <- schools |>\n  st_drop_geometry() |>\n  count(grade_level, name = \"n\", sort = TRUE)\n\nby_grade_org <- schools |>\n  st_drop_geometry() |>\n  count(grade_org, name = \"n\", sort = TRUE)\n\nenroll_summary <- schools |>\n  st_drop_geometry() |>\n  summarize(\n    records_with_enrollment = sum(!is.na(enrollment_num)),\n    median_enrollment       = median(enrollment_num, na.rm = TRUE),\n    mean_enrollment         = mean(enrollment_num, na.rm = TRUE)\n  )\n\nlist(\n  data_source = paste0(\"OpenDataPhilly · \", basename(schools_path)),\n  crs = crs_label,\n  rows = n_schools,\n  bbox_ft = bbox_ft,\n  type_by_specific_head = head(type_by_specific, 10),\n  type_by_code = type_by_code,\n  grade_level = by_grade_level,\n  grade_org = by_grade_org,\n  enrollment_summary = enroll_summary\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data_source\n[1] \"OpenDataPhilly · schools.geojson\"\n\n$crs\n[1] \"EPSG:2272\"\n\n$rows\n[1] 495\n\n$bbox_ft\n     xmin      ymin      xmax      ymax \n2664437.3  219220.6 2745960.0  301940.7 \n\n$type_by_specific_head\n  type_specific   n\n1      DISTRICT 235\n2       CHARTER 102\n3       PRIVATE  99\n4   ARCHDIOCESE  40\n5    CONTRACTED  19\n\n$type_by_code\n  type   n\n1    1 254\n2    3 139\n3    2 102\n\n$grade_level\n              grade_level   n\n1       ELEMENTARY/MIDDLE 202\n2             HIGH SCHOOL 103\n3       ELEMENTARY SCHOOL  85\n4  ELEMENTARY/MIDDLE/HIGH  35\n5           MIDDLE SCHOOL  31\n6             MIDDLE/HIGH  21\n7      PRE-K/KINDERGARTEN   9\n8                UNGRADED   3\n9        PRE-K/ELEMENTARY   2\n10             ELEMENTARY   1\n11 ELEMENTARY?MIDDLE/HIGH   1\n12         SPECIAL CENTER   1\n13                   <NA>   1\n\n$grade_org\n   grade_org   n\n1        K-8 152\n2       9-12 103\n3     PREK-8  50\n4        K-5  45\n5       K-12  18\n6        5-8  16\n7        6-8  16\n8        K-4  12\n9    PREK-12  12\n10      6-12  10\n11    PREK-K  10\n12       K-6   7\n13      7-12   6\n14    PREK-5   5\n15      5-12   4\n16      1-12   3\n17       K-3   3\n18       K-1   2\n19       K-2   2\n20    PREK-3   2\n21    PREK-4   2\n22  UNGRADED   2\n23       1-8   1\n24        12   1\n25       2-5   1\n26      3-12   1\n27       3-5   1\n28       3-6   1\n29       3-8   1\n30       4-8   1\n31      7-10   1\n32      8-12   1\n33       K-7   1\n34    PREK-6   1\n35    PREK-7   1\n\n$enrollment_summary\n  records_with_enrollment median_enrollment mean_enrollment\n1                     333               446        548.4715\n```\n\n\n:::\n:::\n\n\nSchools (School Facilities) – Philadelphia. I chose it to assess educational access equity. School locations allow tract-level coverage analysis and policy-relevant siting insights.\n\nSource: OpenDataPhilly, “School Facilities” (GeoJSON).\nDate: Retrieved for this assignment (documented in code and file list). The layer is maintained by the City of Philadelphia Department of Planning and Development.\n\n495 features in the loaded file.\n\nThe file opened in a geographic CRS (WGS 84).\nI transformed it to EPSG:2272 (NAD83 / Pennsylvania South ftUS) to support feet/miles buffers and area calculations appropriate for Philadelphia.\n---\n\n**Pose a research question**\n\nWhich Philadelphia census tracts with high numbers of school-age children lack walk access (0.5-mile) to an elementary school, and therefore warrant priority investment?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nacs_year   <- 2022\ncrs_feet   <- 2272\nhalf_mile  <- 0.25 * 5280\n\nstopifnot(inherits(schools, \"sf\"), st_crs(schools)$epsg == crs_feet)\n\nelem_schools <- schools |>\n  mutate(\n    go = toupper(trimws(as.character(grade_org))),\n    gl = toupper(trimws(as.character(grade_level))),\n    serves_elem = grepl(\"PREK|K|K-|K–|K TO|K/|^K$|^PREK\", go) |\n                  grepl(\"^-?0?5|^-?0?6|-5|-6\", go) |\n                  grepl(\"ELEMENTARY\", gl)\n  ) |>\n  filter(serves_elem) |>\n  select(school_name, type_specific, grade_org, grade_level)\n\nphl_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", cb = TRUE, year = 2023) |>\n  st_transform(crs_feet) |>\n  select(GEOID)\n\nelem_buf <- elem_schools |>\n  st_buffer(half_mile) |>\n  st_union() |>\n  st_make_valid()\n\nphl_tracts <- phl_tracts |>\n  mutate(tract_area_ft2 = as.numeric(st_area(geometry)))\n\ncovered_parts <- suppressWarnings(st_intersection(phl_tracts, elem_buf))\n\ncover_by_tract <- covered_parts |>\n  mutate(part_area_ft2 = as.numeric(st_area(geometry))) |>\n  st_drop_geometry() |>\n  group_by(GEOID) |>\n  summarize(covered_area_ft2 = sum(part_area_ft2), .groups = \"drop\")\n\nphl_access_elem <- phl_tracts |>\n  left_join(cover_by_tract, by = \"GEOID\") |>\n  mutate(\n    covered_area_ft2 = ifelse(is.na(covered_area_ft2), 0, covered_area_ft2),\n    coverage_pct = pmin(100 * covered_area_ft2 / tract_area_ft2, 100)\n  )\n\nvars_children <- c(\n  male_5_9=\"B01001_004\", male_10_14=\"B01001_005\",\n  fem_5_9 =\"B01001_028\", fem_10_14 =\"B01001_029\"\n)\n\nphl_kids <- get_acs(\n  geography = \"tract\", state = \"PA\", county = \"Philadelphia\",\n  variables = vars_children, survey = \"acs5\", year = acs_year, output = \"wide\"\n) |>\n  transmute(\n    GEOID = as.character(GEOID),\n    child_5_14 = male_5_9E + male_10_14E +\n                 fem_5_9E  + fem_10_14E \n  )\n\nphl_access_elem <- phl_access_elem |>\n  mutate(GEOID = as.character(GEOID)) |>\n  left_join(phl_kids, by = \"GEOID\")\n\nq_child <- quantile(phl_access_elem$child_5_14, 0.75, na.rm = TRUE)\n\nphl_access_elem <- phl_access_elem |>\n  mutate(\n    edu_desert    = coverage_pct <= 10,     \n    high_children = child_5_14 >= q_child,    \n    priority      = edu_desert & high_children\n  )\n\nelem_summary <- phl_access_elem |>\n  st_drop_geometry() |>\n  summarize(\n    tracts      = n(),\n    deserts     = sum(edu_desert, na.rm = TRUE),\n    pct_deserts = round(100 * deserts / tracts, 1),\n    priority_n  = sum(priority, na.rm = TRUE),\n    kids_desert = sum(child_5_14[edu_desert], na.rm = TRUE)\n  )\nprint(elem_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tracts deserts pct_deserts priority_n kids_desert\n1    408      47        11.5          2        8839\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = phl_access_elem, aes(fill = coverage_pct), color = \"white\", size = 0.15) +\n  geom_sf(data = elem_schools, shape = 21, fill = \"black\", color = \"white\", size = 1.2, alpha = 0.85) +\n  geom_sf(data = phl_access_elem |> filter(priority), fill = NA, color = \"#D62728\", linewidth = 0.9) +\n  scale_fill_viridis_c(\n    name = \"Elem. buffer coverage\",\n    labels = label_percent(accuracy = 1, scale = 1),\n    limits = c(0, 100), na.value = \"grey90\", option = \"viridis\"\n  ) +\n  labs(\n    title = \"Philadelphia Elementary School Walk Access (0.5 mile)\",\n    subtitle = \"Priority tracts: high child counts with ≤10% elementary coverage\",\n    caption = \"Sources: OpenDataPhilly School Facilities; ACS 2022 (tidycensus); TIGER/Line tracts\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(face = \"bold\"),\n    plot.title    = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Luciano_Lu_assignment2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nphl_access_elem |>\n  st_drop_geometry() |>\n  filter(priority) |>\n  select(GEOID, coverage_pct, child_5_14) |>\n  arrange(desc(child_5_14))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        GEOID coverage_pct child_5_14\n1 42101034802     4.242087       1077\n2 42101009300     8.411688        694\n```\n\n\n:::\n:::\n\n\n\nWhy this projection?\n\nI run all operations in EPSG:2272 (NAD83 / Pennsylvania South ftUS). This StatePlane system minimizes distortion over Philadelphia and uses feet, which fits walk buffers and area calculations in miles/feet. The city publishes many layers in this CRS, so joins stay precise and distances do not inherit Web-Mercator scale errors.\n\nWhy a 0.25-mile threshold for younger students?\n\n0.25 mile ≈ 1,320 ft ≈ a 5-minute walk at ~3 mph (3 mi/hr → 264 ft/min; 5 min → 1,320 ft). A five-minute target reflects comfort and supervision needs for younger children.\nElementary pupils often walk more slowly, face more frequent stops, and require safer crossings. A 0.25-mile standard sets a conservative, child-appropriate access goal; 0.5 mile remains a reasonable secondary benchmark for older students and caregivers.\n\nThe map shows high elementary walk access across the urban core. Coverage drops at the edges of the city and in a few industrial or low-density tracts. With a 0.5-mile buffer, only a small share of tracts qualify as “deserts,” and most do not have large child populations. A stricter 0.25-mile buffer reveals more low-coverage tracts and brings a few high-child-count areas (42101034802 and 42101009300) into view. These priority tracts warrant near-term attention through safe-routes upgrades, school siting adjustments, or co-located youth services.\n\n## Finally - A few comments about your incorporation of feedback!\nAfter the first assignment, I focused on making my analysis more structured and easier to read. I reorganized the Markdown file by grouping related visuals and adding short introductory sentences before each figure to explain its purpose.\n\n",
    "supporting": [
      "Luciano_Lu_assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}