{
  "hash": "df7f3c0cd2d87957bacbba1cfb5c394b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Luciano\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Assignment Overview\n\n## Scenario\n\nYou are a data analyst for the **Missouri Department of Human Services**. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.\n\nDrawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.\n\n## Learning Objectives\n\n- Apply dplyr functions to real census data for policy analysis\n- Evaluate data quality using margins of error \n- Connect technical analysis to algorithmic decision-making\n- Identify potential equity implications of data reliability issues\n- Create professional documentation for policy stakeholders\n\n## Submission Instructions\n\n**Submit by posting your updated portfolio link on Canvas.** Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/`\n\nMake sure to update your `_quarto.yml` navigation to include this assignment under an \"Assignments\" menu.\n\n# Part 1: Portfolio Integration\n\nCreate this assignment in your portfolio repository under an `assignments/assignment_1/` folder structure. Update your navigation menu to include:\n\n```\n- text: Assignments\n  menu:\n    - href: assignments/assignment_1/assignment_1.qmd\n      text: \"Assignment 1: Census Data Exploration\"\n```\nIf there is a special character like comma, you need use double quote mark so that the quarto can identify this as text\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\n\n# Set your Census API key\ncensus_api_key(\"b236a5b2547ce79c3e203c3e1366ed7fa7b3d463\", install = FALSE)\nSys.getenv(\"CENSUS_API_KEY\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"b236a5b2547ce79c3e203c3e1366ed7fa7b3d463\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Choose your state for analysis\nmy_state <- \"Missouri\"\n```\n:::\n\n\n**State Selection:** I have chosen **Missouri** for this analysis because: major metropolitan areas (like St. Louis and Kansas City) with a large number of rural counties. This scenario can help to illustrate how data quality may vary between urban and rural areas, which is important for equitable policy decisions.\n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n**Your Task:** Use `get_acs()` to retrieve county-level data for your chosen state.\n\n**Requirements:**\n- Geography: county level\n- Variables: median household income (B19013_001) and total population (B01003_001)  \n- Year: 2022\n- Survey: acs5\n- Output format: wide\n\n**Hint:** Remember to give your variables descriptive names using the `variables = c(name = \"code\")` syntax.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Retrieve county-level ACS data for Missouri\ncounty_data <- get_acs(\n  geography = \"county\",\n  state = my_state,\n  variables = c(\n    median_income = \"B19013_001\",\n    total_pop = \"B01003_001\"\n  ),\n  year   = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\n# Clean county names: remove \", Missouri\" and \" County\"\ncounty_data <- county_data %>%\n  mutate(NAME = str_remove(NAME, \", Missouri\"),\n         NAME = str_remove(NAME, \" County\"))\n\n# Display the first few rows\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME     median_incomeE median_incomeM total_popE total_popM\n  <chr> <chr>             <dbl>          <dbl>      <dbl>      <dbl>\n1 29001 Adair             51020           4430      25299         NA\n2 29003 Andrew            68774           4776      18069         NA\n3 29005 Atchison          58521           3686       5270         NA\n4 29007 Audrain           51745           2309      24873         NA\n5 29009 Barry             55592           5385      34701         NA\n6 29011 Barton            48105           5576      11683         NA\n```\n\n\n:::\n:::\n\n\n## 2.2 Data Quality Assessment\n\n**Your Task:** Calculate margin of error percentages and create reliability categories.\n\n**Requirements:**\n- Calculate MOE percentage: (margin of error / estimate) * 100\n- Create reliability categories:\n  - High Confidence: MOE < 5%\n  - Moderate Confidence: MOE 5-10%  \n  - Low Confidence: MOE > 10%\n- Create a flag for unreliable estimates (MOE > 10%)\n\n**Hint:** Use `mutate()` with `case_when()` for the categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(stringr)\n\nincome_reliability <- county_data %>%\n  mutate(income_moe_pct = if_else(\n      median_incomeE > 0,\n      100 * median_incomeM / median_incomeE,\n      NA_real_\n  ),\n  reliability = case_when(\n      income_moe_pct < 5 ~ \"High Confidence\",\n      income_moe_pct >= 5 & income_moe_pct <= 10 ~ \"Moderate Confidence\",\n      income_moe_pct > 10 ~ \"Low Confidence\",\n      TRUE ~ NA_character_\n  ),\n  unreliable_flag = if_else(income_moe_pct > 10, TRUE, FALSE),\n  total_popE = if_else(total_popE < 0, NA_real_, total_popE\n  )) %>%\n  select(GEOID, NAME, median_incomeE, median_incomeM, income_moe_pct, reliability, unreliable_flag, total_popE)\n\n# Display the first few rows\nhead(income_reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GEOID NAME     median_incomeE median_incomeM income_moe_pct reliability       \n  <chr> <chr>             <dbl>          <dbl>          <dbl> <chr>             \n1 29001 Adair             51020           4430           8.68 Moderate Confiden…\n2 29003 Andrew            68774           4776           6.94 Moderate Confiden…\n3 29005 Atchison          58521           3686           6.30 Moderate Confiden…\n4 29007 Audrain           51745           2309           4.46 High Confidence   \n5 29009 Barry             55592           5385           9.69 Moderate Confiden…\n6 29011 Barton            48105           5576          11.6  Low Confidence    \n# ℹ 2 more variables: unreliable_flag <lgl>, total_popE <dbl>\n```\n\n\n:::\n:::\n\n\n## 2.3 High Uncertainty Counties\n\n**Your Task:** Identify the 5 counties with the highest MOE percentages.\n\n**Requirements:**\n- Sort by MOE percentage (highest first)\n- Select the top 5 counties\n- Display: county name, median income, margin of error, MOE percentage, reliability category\n- Format as a professional table using `kable()`\n\n**Hint:** Use `arrange()`, `slice()`, and `select()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create table of top 5 counties by MOE percentage\nlibrary(knitr)\n\ntop5_uncertain <- income_reliability %>%\n  arrange(desc(income_moe_pct)) %>%\n  slice(1:5) %>%\n  select(\n    County = NAME,\n    total_popE = total_popE,\n    `Median Income (Estimate)` = median_incomeE,\n    `Margin of Error` = median_incomeM,\n    `MOE %` = income_moe_pct,\n    `Reliability` = reliability\n  )\n\n# Format as table with kable() - include appropriate column names and caption\nkable(\n  top5_uncertain,\n  caption = \"Top 5 Counties with Highest Median Income MOE Percentages in Missouri\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 Counties with Highest Median Income MOE Percentages in Missouri\n\n|County      | total_popE| Median Income (Estimate)| Margin of Error|    MOE %|Reliability    |\n|:-----------|----------:|------------------------:|---------------:|--------:|:--------------|\n|Shannon     |       7132|                    46767|            9920| 21.21154|Low Confidence |\n|Carter      |       5299|                    45737|            8517| 18.62168|Low Confidence |\n|Mississippi |      12305|                    40833|            7546| 18.48015|Low Confidence |\n|Ozark       |       8688|                    39125|            7092| 18.12652|Low Confidence |\n|Mercer      |       3517|                    55592|           10045| 18.06915|Low Confidence |\n\n\n:::\n:::\n\n\n**Data Quality Commentary:**\n\nThe top five counties all have populations of around 40,000 to 60,000 or even fewer. For example, Mercer has just over 50,000 residents, yet its MOE reaches 18%. This suggests that smaller populations may lead to higher uncertainty in estimates, likely due to smaller sample sizes in the ACS survey. Carter, Shannon, and Ozark are located in Missouri’s Ozark region, an area characterized by both limited resources and highly dispersed populations. These factors can contribute to challenges in data collection, resulting in less reliable estimates.\n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n**Your Task:** Select 2-3 counties from your reliability analysis for detailed tract-level study.\n\n**Strategy:** Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use filter() to select 2-3 counties from your county_reliability data\n# Store the selected counties in a variable called selected_counties\nselected_counties <- income_reliability %>%\n  filter(\n    NAME %in% c(\"St. Louis\",    # High Confidence\n                \"Buchanan\",      # Moderate Confidence\n                \"Texas\")     # Low Confidence\n  ) %>%\n  select(\n    County = NAME,\n    `Median Income (Estimate)` = median_incomeE,\n    `MOE %` = income_moe_pct,\n    `Reliability` = reliability\n  )\n\n# Display the selected counties with their key characteristics\n# Show: county name, median income, MOE percentage, reliability category\nselected_counties\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  County    `Median Income (Estimate)` `MOE %` Reliability        \n  <chr>                          <dbl>   <dbl> <chr>              \n1 Buchanan                       58303    5.07 Moderate Confidence\n2 St. Louis                      78067    1.64 High Confidence    \n3 Texas                          42870   11.4  Low Confidence     \n```\n\n\n:::\n:::\n\n\n**Comment on the output:** I selected St. Louis, Buchanan, and Texas counties to represent high, moderate, and low data reliability contexts—urban, mid-sized, and rural areas, respectively. \n\n## 3.2 Tract-Level Demographics\n\n**Your Task:** Get demographic data for census tracts in your selected counties.\n\n**Requirements:**\n- Geography: tract level\n- Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)\n- Use the same state and year as before\n- Output format: wide\n- **Challenge:** You'll need county codes, not names. Look at the GEOID patterns in your county data for hints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your race/ethnicity variables with descriptive names\nrace_vars <- c(\n  total_pop = \"B03002_001\",\n  white     = \"B03002_003\",\n  black     = \"B03002_004\",\n  hispanic  = \"B03002_012\"\n)\n\n# Use get_acs() to retrieve tract-level data\n# Hint: You may need to specify county codes in the county parameter\ncounty_codes <- income_reliability %>%\n  filter(NAME %in% selected_counties$County) %>%\n  transmute(county_code = str_sub(GEOID, 3, 5)) %>%\n  distinct() %>%\n  pull(county_code)\ntract_demo_raw <- get_acs(\n  geography = \"tract\",\n  state     = my_state,\n  county    = county_codes,\n  variables = race_vars,\n  year      = 2022,\n  survey    = \"acs5\",\n  output    = \"wide\"\n)\n\n\n# Create percentages for white, Black, and Hispanic populations\ntract_demo <- tract_demo_raw %>%\n  mutate(\n    white_pct    = if_else(total_popE > 0, 100 * whiteE   / total_popE, NA_real_),\n    black_pct    = if_else(total_popE > 0, 100 * blackE   / total_popE, NA_real_),\n    hispanic_pct = if_else(total_popE > 0, 100 * hispanicE/ total_popE, NA_real_),\n    total_population = total_popE,\n    tract_name   = str_extract(NAME, \"Census Tract[^,]+\"),\n    county_name  = str_extract(NAME, \"Census Tract[^,]+\")) %>%\n  select(\n    GEOID, tract_name, county_name,\n    total_population, whiteE, blackE, hispanicE,\n    white_pct, black_pct, hispanic_pct\n  )\n\n\ntract_demo <- tract_demo %>%\n  mutate(\n    county_name = county_name %>%\n      str_replace_all(\",\", \";\") %>%\n      { str_split_fixed(., \";\", 3)[, 2] } %>%\n      str_trim()\n  )\n\n# Add readable tract and county name columns using str_extract() or similar\nkable(\n  head(tract_demo, 10),\n  caption = \"Selected Counties: Tract-Level Race/Ethnicity (ACS 2018–2022)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Selected Counties: Tract-Level Race/Ethnicity (ACS 2018–2022)\n\n|GEOID       |tract_name                                   |county_name     | total_population| whiteE| blackE| hispanicE| white_pct| black_pct| hispanic_pct|\n|:-----------|:--------------------------------------------|:---------------|----------------:|------:|------:|---------:|---------:|---------:|------------:|\n|29021000100 |Census Tract 1; Buchanan County; Missouri    |Buchanan County |             5914|   4906|    265|       123|  82.95570|  4.480893|     2.079811|\n|29021000200 |Census Tract 2; Buchanan County; Missouri    |Buchanan County |             4522|   3369|    100|       622|  74.50243|  2.211411|    13.754976|\n|29021000300 |Census Tract 3; Buchanan County; Missouri    |Buchanan County |             2571|   2030|     75|       283|  78.95760|  2.917153|    11.007390|\n|29021000400 |Census Tract 4; Buchanan County; Missouri    |Buchanan County |             1444|   1205|     43|        57|  83.44875|  2.977839|     3.947368|\n|29021000500 |Census Tract 5; Buchanan County; Missouri    |Buchanan County |             3077|   2453|     96|       399|  79.72051|  3.119922|    12.967176|\n|29021000600 |Census Tract 6; Buchanan County; Missouri    |Buchanan County |             4836|   3535|    496|       288|  73.09760| 10.256410|     5.955335|\n|29021000701 |Census Tract 7.01; Buchanan County; Missouri |Buchanan County |             4567|   3554|    387|       505|  77.81914|  8.473834|    11.057587|\n|29021000702 |Census Tract 7.02; Buchanan County; Missouri |Buchanan County |             4198|   3475|    226|       201|  82.77751|  5.383516|     4.787994|\n|29021000900 |Census Tract 9; Buchanan County; Missouri    |Buchanan County |             4500|   3432|    431|       382|  76.26667|  9.577778|     8.488889|\n|29021001000 |Census Tract 10; Buchanan County; Missouri   |Buchanan County |             2149|   1456|    382|       161|  67.75244| 17.775710|     7.491857|\n\n\n:::\n:::\n\n\n## 3.3 Demographic Analysis\n\n**Your Task:** Analyze the demographic patterns in your selected areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the tract with the highest percentage of Hispanic/Latino residents\n# Hint: use arrange() and slice() to get the top tract\ntop_hispanic_tract <- tract_demo %>%\n  arrange(desc(hispanic_pct)) %>%\n  slice(1) %>%\n  select(\n    GEOID, tract_name, county_name, total_population,\n    white_pct, black_pct, hispanic_pct\n  )\n\nkable(\n  top_hispanic_tract,\n  caption = \"Tract with Highest Hispanic/Latino Percentage (Selected Counties)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Tract with Highest Hispanic/Latino Percentage (Selected Counties)\n\n|GEOID       |tract_name                                    |county_name      | total_population| white_pct| black_pct| hispanic_pct|\n|:-----------|:---------------------------------------------|:----------------|----------------:|---------:|---------:|------------:|\n|29189214700 |Census Tract 2147; St. Louis County; Missouri |St. Louis County |             8305|  43.66045|  18.81999|     32.51054|\n\n\n:::\n\n```{.r .cell-code}\n# Calculate average demographics by county using group_by() and summarize()\ncounty_summary_unweighted <- tract_demo %>%\n  group_by(county_name) %>%\n  summarise(\n    n_tracts = n(),\n    avg_white_pct    = mean(white_pct,    na.rm = TRUE),\n    avg_black_pct    = mean(black_pct,    na.rm = TRUE),\n    avg_hispanic_pct = mean(hispanic_pct, na.rm = TRUE)\n  ) %>%\n  arrange(desc(avg_hispanic_pct))\n\n# Show: number of tracts, average percentage for each racial/ethnic group\n# Create a nicely formatted table of your results using kable()\nkable(\n  county_summary_unweighted,\n  caption = \"Average Demographics by County\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Demographics by County\n\n|county_name      | n_tracts| avg_white_pct| avg_black_pct| avg_hispanic_pct|\n|:----------------|--------:|-------------:|-------------:|----------------:|\n|Buchanan County  |       26|      80.95432|      5.691374|         7.305424|\n|St. Louis County |      236|      61.42962|     26.113783|         3.002732|\n|Texas County     |        8|      90.21293|      1.883072|         2.467462|\n\n\n:::\n:::\n\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n**Your Task:** Examine margins of error for demographic variables to see if some communities have less reliable data.\n\n**Requirements:**\n- Calculate MOE percentages for each demographic variable\n- Flag tracts where any demographic variable has MOE > 15%\n- Create summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentages for white, Black, and Hispanic variables\n# Hint: use the same formula as before (margin/estimate * 100)\nmoe_pct <- tract_demo_raw %>%\n  transmute(\n    GEOID,\n    white_moe_pct    = if_else(whiteE    > 0, 100 * whiteM    / whiteE,    NA_real_),\n    black_moe_pct    = if_else(blackE    > 0, 100 * blackM    / blackE,    NA_real_),\n    hispanic_moe_pct = if_else(hispanicE > 0, 100 * hispanicM / hispanicE, NA_real_)\n  )\n\n# Create a flag for tracts with high MOE on any demographic variable\n# Use logical operators (| for OR) in an ifelse() statement\ntract_quality <- tract_demo %>%\n  select(GEOID, county_name, tract_name, total_population,\n         white_pct, black_pct, hispanic_pct) %>%\n  left_join(moe_pct, by = \"GEOID\") %>%\n  mutate(\n    high_moe_flag = ifelse(\n      coalesce(white_moe_pct    > 50, FALSE) |\n      coalesce(black_moe_pct    > 50, FALSE) |\n      coalesce(hispanic_moe_pct > 50, FALSE),\n      TRUE, FALSE\n    )\n  )\n\n# Create summary statistics showing how many tracts have data quality issues\noverall_summary <- tract_quality %>%\n  summarise(\n    n_tracts       = n(),\n    n_high_moe     = sum(high_moe_flag, na.rm = TRUE),\n    share_high_moe = round(100 * n_high_moe / n_tracts, 1)\n  )\nkable(overall_summary, caption = \"Overall count and share of high-MOE tracts\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Overall count and share of high-MOE tracts\n\n| n_tracts| n_high_moe| share_high_moe|\n|--------:|----------:|--------------:|\n|      270|        255|           94.4|\n\n\n:::\n\n```{.r .cell-code}\ncounty_summary <- tract_quality %>%\n  group_by(county_name) %>%\n  summarise(\n    n_tracts       = n(),\n    n_high_moe     = sum(high_moe_flag, na.rm = TRUE),\n    share_high_moe = round(100 * n_high_moe / n_tracts, 1)\n  ) %>%\n  arrange(desc(share_high_moe), desc(n_high_moe))\nkable(county_summary, caption = \"High-MOE tracts by county\")\n```\n\n::: {.cell-output-display}\n\n\nTable: High-MOE tracts by county\n\n|county_name      | n_tracts| n_high_moe| share_high_moe|\n|:----------------|--------:|----------:|--------------:|\n|Buchanan County  |       26|         26|          100.0|\n|St. Louis County |      236|        223|           94.5|\n|Texas County     |        8|          6|           75.0|\n\n\n:::\n:::\n\n\n## 4.2 Pattern Analysis\n\n**Your Task:** Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group tracts by whether they have high MOE issues\n# Calculate average characteristics for each group:\n# - population size, demographic percentages\npattern_summary <- tract_quality %>%\n  group_by(high_moe_flag) %>%\n  summarise(\n    n_tracts          = n(),\n    avg_population    = mean(total_population, na.rm = TRUE),\n    avg_white_pct     = mean(white_pct, na.rm = TRUE),\n    avg_black_pct     = mean(black_pct, na.rm = TRUE),\n    avg_hispanic_pct  = mean(hispanic_pct, na.rm = TRUE)\n  )\n\n# Use group_by() and summarize() to create this comparison\n# Create a professional table showing the patterns\nkable(\n  pattern_summary,\n  caption = \"Comparison of Community Characteristics by Data Quality Flag\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Community Characteristics by Data Quality Flag\n\n|high_moe_flag | n_tracts| avg_population| avg_white_pct| avg_black_pct| avg_hispanic_pct|\n|:-------------|--------:|--------------:|-------------:|-------------:|----------------:|\n|FALSE         |       15|       4488.133|      35.73905|      53.43592|         4.259571|\n|TRUE          |      255|       4085.306|      65.83459|      21.66414|         3.350713|\n\n\n:::\n:::\n\n\n**Pattern Analysis:** \nEven after raising the threshold for high margins of error from 15% to 50%, nearly 94% of tracts remain flagged as high-MOE. Such an extreme distribution calls the reliability of the data into question: either the ACS sample sizes in these counties are insufficient, or the estimation procedures struggle to produce stable values in small communities. \nSome results are also counterintuitive. For instance, certain tracts with larger populations and higher shares of minority residents appear to have lower error rates—a pattern that challenges expectations. \nAt this stage, it is difficult to draw substantive conclusions; what emerges most clearly is the presence of potential bias and instability within the data itself.\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n**Your Task:** Write an executive summary that integrates findings from all four analyses.\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\n**Executive Summary:**\n\nThe analysis shows that data reliability problems are not randomly distributed but concentrated in specific variables and geographies. At the county level, median household income estimates (B19013_001) exhibit much higher margins of error in small, rural counties: Shannon (21.2%), Carter (18.6%), Mississippi (18.5%), Ozark (18.1%), and Mercer (18.1%) all far exceed the 10% threshold, while larger metropolitan counties such as St. Louis report far lower error rates (1.64%). At the tract level, racial and ethnic variables (B03002) are especially unstable when minority group counts are small. Using a 50% MOE threshold, 94.4% of tracts were flagged as high-MOE, with Black and Hispanic estimates most often responsible for the flag. This pattern is stark in predominantly white, rural counties such as Buchanan (100% of tracts flagged) and Texas (75%), where Black and Hispanic groups make up less than 10% of the population. Even in St. Louis County, where the sample base is larger, 94.5% of tracts still exceeded the threshold, largely because Hispanic residents constitute only 3% of the county population.\n\nBecause algorithms allocate resources based on point estimates without accounting for their uncertainty, unstable figures can translate directly into misclassification. In rural tracts with very small Black or Hispanic populations, ACS samples often produce highly volatile estimates. An algorithm that interprets these values at face value may conclude that such communities have little or no need for targeted services, even when real needs exist. Conversely, areas where small samples happen to inflate minority counts could be over-prioritized. The core risk is that statistical noise is treated as social reality, where parts of the already vulnerable groups are more exposed to under-investment.\n\nThe ACS is a very sample survey. 1. For a large city or county, hundreds of households might be surveyed, with estimate of median income and demographic counts. For a tiny county, only a handful of households are surveyed; 2. When a population has a dominant majority and a few minority members, the minority data will have high variance. Missouri’s rural counties often have very few minority residents, and thus data about those residents is scant and uncertain. If the algorithm tries to pinpoint, say, where to fund a minority outreach program, it might miss small communities entirely due to these data gaps. 3. Some communities (e.g., very low-income households, remote rural residents, certain ethnic minorities, immigrants) have historically lower response rates to the census and surveys. Language barriers, distrust in government, or simply being hard to reach (like no internet, P.O. box addresses, etc.) can lead to undercounting. That means the ACS might not just have statistical uncertainty, but actual systematic bias in who is represented.\n\nThe algorithm should not treat all data points equally. Wherever possible, include the margin of error or a confidence weight in the algorithm’s calculations. For example, if ranking counties by median income (lowest income = highest need), adjust the ranking to account for MOE. A county with an income of $40k ± $8k should be considered as uncertain and perhaps be grouped with counties that have say $35k median ± $2k, rather than confidently placing it above or below them. Set rules that flag communities (counties or tracts) with low data confidence for manual review. If the data is too poor, don’t let the algorithm alone make the call. For instance, the algorithm could produce a preliminary list of priority areas but mark any area with “Low Confidence” data (like those >10% MOE counties, or tracts with >50% MOE on key stats) for human analysts to double-check. This ensures places like Shannon County or Texas County are not ignored just because of shaky data.\n\n## 6.3 Specific Recommendations\n\n**Your Task:** Create a decision framework for algorithm implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table using your county reliability data\n# Include: county name, median income, MOE percentage, reliability category\n\n# Add a new column with algorithm recommendations using case_when():\n# - High Confidence: \"Safe for algorithmic decisions\"\n# - Moderate Confidence: \"Use with caution - monitor outcomes\"  \n# - Low Confidence: \"Requires manual review or additional data\"\nrecommendations <- income_reliability %>%\n  mutate(\n    recommendation = case_when(\n      reliability == \"High Confidence\" ~ \"Safe for algorithmic decisions\",\n      reliability == \"Moderate Confidence\" ~ \"Use with caution - monitor outcomes\",\n      reliability == \"Low Confidence\" ~ \"Requires manual review or additional data\",\n      TRUE ~ NA_character_\n    )\n  ) %>%\n  select(\n    County = NAME,\n    `Median Income (Estimate)` = median_incomeE,\n    `MOE %` = income_moe_pct,\n    `Reliability` = reliability,\n    Recommendation = recommendation\n  )\n\nkable(\n  head(recommendations, 10),\n  caption = \"Decision Framework for Algorithm Implementation\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Decision Framework for Algorithm Implementation\n\n|County    | Median Income (Estimate)|     MOE %|Reliability         |Recommendation                            |\n|:---------|------------------------:|---------:|:-------------------|:-----------------------------------------|\n|Adair     |                    51020|  8.682870|Moderate Confidence |Use with caution - monitor outcomes       |\n|Andrew    |                    68774|  6.944485|Moderate Confidence |Use with caution - monitor outcomes       |\n|Atchison  |                    58521|  6.298594|Moderate Confidence |Use with caution - monitor outcomes       |\n|Audrain   |                    51745|  4.462267|High Confidence     |Safe for algorithmic decisions            |\n|Barry     |                    55592|  9.686646|Moderate Confidence |Use with caution - monitor outcomes       |\n|Barton    |                    48105| 11.591311|Low Confidence      |Requires manual review or additional data |\n|Bates     |                    54122|  9.574665|Moderate Confidence |Use with caution - monitor outcomes       |\n|Benton    |                    50229|  7.722630|Moderate Confidence |Use with caution - monitor outcomes       |\n|Bollinger |                    52306| 16.525829|Low Confidence      |Requires manual review or additional data |\n|Boone     |                    66564|  2.665104|High Confidence     |Safe for algorithmic decisions            |\n\n\n:::\n\n```{.r .cell-code}\n# Format as a professional table with kable()\n```\n:::\n\n\n**Key Recommendations:**\n\n**Your Task:** Use your analysis results to provide specific guidance to the department.\n\n1. **Counties suitable for immediate algorithmic implementation:** \nMajor metropolitan and other large counties with reliable data (High Confidence). For Missouri, these include places like St. Louis County, St. Louis City, Jackson County, St. Charles County, Clay County, Greene County, and a few others. These areas have MOEs well under 5% for key metrics. The department can confidently use the algorithm to drive decisions in these locales because any ranking or prioritization based on ACS data is grounded in fairly accurate information. \n\n2. **Counties requiring additional oversight:** \nMid-sized or somewhat smaller counties with moderate data confidence. This list might include Buchanan, Boone, Cole, Jasper, Newton, Platte, Cape Girardeau, etc., roughly counties with populations in the few tens of thousands up to around 100k. In these cases, the algorithm’s output should be reviewed by staff. For instance, if the algorithm ranks Buchanan County as the 10th highest need, because of moderate MOE, staff might double-check recent economic conditions in Buchanan (maybe there was a plant closure not reflected fully in the 2018–2022 data, or maybe the MOE means it could actually rank 8th or 12th). For example, if funds were given to a county for outreach but uptake is low, was it because the need was overestimated? Or if a county not prioritized starts showing signs of distress, was it an oversight due to data noise? Essentially\n\n3. **Counties needing alternative approaches:** \nCounties with low confidence data (mostly rural counties and those flagged earlier like Shannon, Carter, Ozark, Mississippi, Mercer, and many others). In these cases, I recommend manual review and supplementary analysis as a prerequisite for decision-making. The algorithm might initially rank these places oddly (perhaps not high need because of an overestimated median income or not low need because of a weird population estimate).\na. Look at local poverty indicators (e.g., school district free lunch percentages, local food pantry demand).\nb. Consult qualitative reports (maybe county commissioners or local non-profits can speak to the community’s situation).\nc. Possibly use regional grouping: If one county’s data is flaky, consider looking at a cluster of surrounding similar counties to infer needs.\n\n## Questions for Further Investigation\n\na. We observed that many of the highest-MOE counties cluster in certain regions (e.g., the Ozarks). A deeper spatial analysis could reveal regional trends. So, are there geographic clusters of poor data quality?\nb. It would be insightful to examine if data reliability is improving or worsening over time. For instance, how do the 2018–2022 ACS margins of error compare to 2010–2014 ACS for these same counties?\nc. We focused on median income and a few racial groups. What about other variables that an algorithm might use? For example, poverty rates, unemployment rates, education levels, or age distributions by tract/county.\nd. what factors best predict high MOE or data issues? Our analysis suggests population size and homogeneity are factors. We could formally test correlations: e.g., does a lower response rate or a higher proportion of rental housing correlate with higher MOEs?\n\n# Technical Notes\n\n**Data Sources:** \nAll data for this analysis comes from the U.S. Census Bureau’s American Community Survey (ACS) 2018–2022 5-Year Estimates. The data was accessed via the tidycensus R package. Key tables used were:\n\nB19013: Median Household Income in the Past 12 Months (in 2022 inflation-adjusted dollars) – for county-level median income and MOE.\nB01003: Total Population – for county populations.\nB03002: Hispanic or Latino Origin by Race – for tract-level total population and breakdown by White (non-Hispanic), Black (non-Hispanic), and Hispanic (any race) populations and their MOEs.\n\n**Reproducibility:** \nThe analysis was conducted using R (version 4.x) and the following main packages: tidycensus for data retrieval, tidyverse (dplyr, stringr) for data manipulation, and knitr/kable for presenting tables. A Census API key (personal to the analyst) was used to authenticate data requests; this key is required to replicate the data pulls. All code and documentation for this analysis are available in \n\n**Methodology Notes:**\na. Reliability Thresholds: We defined “High”, “Moderate”, and “Low” confidence using specific MOE percentage cutoffs (5% and 10%). These thresholds are somewhat arbitrary but are common sense rules of thumb in survey analysis. A 5% MOE indicates a very tight estimate, while beyond 10% starts to indicate caution.\nb. High MOE Flag at Tract Level: I chose a 50% MOE as the flag criterion for tract-level demographic data. The assignment prompt mentioned 15% as a possible threshold to consider “unreliable,” but we observed that using 15% would flag virtually every tract. This decision was to focus discussion on the worst data problems; however, it means we understate the prevalence of “moderate” data issues. In reality, even a 20% MOE might be problematic for decision-making, so our approach was a conservative one.\nc. County Selection: We intentionally picked one county for each reliability category to compare (rather than random selection). This allowed us to illustrate contrasts, but it means some findings (like patterns in St. Louis vs. Texas County) are examples, not exhaustive. If a different high confidence county were chosen (say, Jackson County instead of St. Louis County), many patterns would be similar, but specific numbers would differ.\n\n**Limitations:**\nMargin of Error Interpretation: All MOEs discussed are at the 90% confidence level. This means there is a 10% chance the true value lies outside the given interval. If one prefers 95% confidence, margins would be wider. For simplicity, we stuck to ACS’s MOE as given.\nACS Data Limitations: The ACS 5-year data, while comprehensive, has known limitations. Small or hard-to-reach populations (e.g., homeless individuals, transient laborers, undocumented immigrants) may be undercounted. Our analysis doesn’t correct for any undercount bias; it only measures sampling error (MOE).\n---\n\n## Submission Checklist\n\nBefore submitting your portfolio link on Canvas:\n\n- [ ] All code chunks run without errors\n- [ ] All \"[Fill this in]\" prompts have been completed\n- [ ] Tables are properly formatted and readable\n- [ ] Executive summary addresses all four required components\n- [ ] Portfolio navigation includes this assignment\n- [ ] Census API key is properly set \n- [ ] Document renders correctly to HTML\n\n**Remember:** Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/your_file_name.html`",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}